# Generated by Django 3.2.6 on 2021-11-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_review_movie_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
